"""
Module 1: Change Detection

Takes raw vendor changelog entries and converts each into a structured
change record using the prompt in prompts/module1_change_detection.txt.

Runs in one of two modes:
  - REAL mode: if ANTHROPIC_API_KEY is set, calls the Claude API using the
    prompt file, so the extraction is genuinely LLM-driven.
  - MOCK mode: if no key is set, returns pre-computed extractions for the
    three known sample changelog entries, so the demo runs for anyone who
    clones the repo without needing credentials.

Mock outputs were generated by actually running this prompt against Claude
once, then frozen here — they are not hand-written guesses.
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))  # lets this run standalone too
from modules.llm_client import call_llm, active_provider, clean_json_text

PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "module1_change_detection.txt"
RAW_DATA_PATH = Path(__file__).parent.parent / "data" / "stripe_changelog_raw.json"

MOCK_RESULTS = {
    "Charges API deprecated in favor of PaymentIntents": {
        "change_id": "charges-to-payment-intents",
        "date": "2019-02-19",
        "type": "deprecation",
        "sdk_method": "stripe.Charge.create",
        "endpoint": "POST /v1/charges",
        "old_pattern": "Direct calls to stripe.Charge.create(...) for taking a card payment",
        "new_pattern": "stripe.PaymentIntent.create(...) followed by confirmation",
        "migration_note": "Replace stripe.Charge.create with stripe.PaymentIntent.create so the payment supports SCA/3D Secure 2.",
        "severity": "medium",
        "requires_action": True
    },
    "sources parameter removed from PaymentIntent confirmation": {
        "change_id": "source-param-removed",
        "date": "2022-08-01",
        "type": "breaking",
        "sdk_method": "stripe.PaymentIntent.confirm",
        "endpoint": "POST /v1/payment_intents/:id/confirm",
        "old_pattern": "stripe.PaymentIntent.confirm(id, source=...)",
        "new_pattern": "stripe.PaymentIntent.confirm(id, payment_method=...)",
        "migration_note": "Replace the 'source' argument with 'payment_method' when confirming a PaymentIntent.",
        "severity": "high",
        "requires_action": True
    },
    "New feature: automatic_payment_methods on PaymentIntent": {
        "change_id": "automatic-payment-methods",
        "date": "2023-10-16",
        "type": "feature",
        "sdk_method": "stripe.PaymentIntent.create",
        "endpoint": "POST /v1/payment_intents",
        "old_pattern": "Manually listing payment_method_types=[...] on PaymentIntent.create",
        "new_pattern": "automatic_payment_methods={'enabled': True} on PaymentIntent.create",
        "migration_note": "Optionally replace manual payment_method_types with automatic_payment_methods to let Stripe manage available methods.",
        "severity": "low",
        "requires_action": False
    }
}


def _call_llm_for_change(raw_entry_text: str) -> dict:
    prompt_template = PROMPT_PATH.read_text()
    prompt = prompt_template.replace("{RAW_ENTRY}", raw_entry_text)
    text = call_llm(prompt, max_tokens=900)
    return json.loads(clean_json_text(text))


def detect_changes() -> list[dict]:
    """
    Returns a list of structured change records, one per raw changelog entry.
    Each record also carries the raw_text/title so the UI can show input -> output.
    """
    raw_entries = json.loads(RAW_DATA_PATH.read_text())
    use_real = active_provider() != "mock"

    results = []
    for entry in raw_entries:
        if use_real:
            structured = _call_llm_for_change(entry["raw_text"])
        else:
            structured = MOCK_RESULTS[entry["title"]]
        results.append({
            "input_title": entry["title"],
            "input_raw_text": entry["raw_text"],
            "structured": structured
        })
    return results


if __name__ == "__main__":
    # Quick manual test: run this file directly to sanity check module 1 alone.
    out = detect_changes()
    print(json.dumps(out, indent=2))
    print(f"\nMode: {active_provider()}")
    print(f"Parsed {len(out)} changelog entries.")
